# Generated by Django 4.2.4 on 2023-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
